# Generated by Django 5.1 on 2025-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(help_text="Phrase d'accroche affichée sur l'accueil", max_length=255)),
                ('history', models.TextField(help_text="Historique de l'entreprise")),
                ('mission', models.TextField(blank=True, help_text="Mission de l'entreprise", null=True)),
                ('vision', models.TextField(blank=True, help_text="Vision de l'entreprise", null=True)),
                ('values', models.TextField(blank=True, help_text='Valeurs fondamentales', null=True)),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='company/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
