# Generated by Django 5.1 on 2025-02-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='word_of_director',
            field=models.TextField(help_text="Mots de directeur de l'entreprise", null=True),
        ),
    ]
